language: node_js
node_js:
- '8'
- '10'
- '12'
- '14'
services:
- mongodb
notifications:
  email:
    on_success: never
env:
  global:
    secure: Co69IcmSoK92G4czSNE3GpSmqqzcy2dh/cFUNaDw4DWbF/z7ztaKdksJ7SqfzuIZCp0b1578o9GV8CVHSY+zJi3+UA65nh8jG4u161YhYvJxU2TleId+TfbrmK0vPBtmuUHJKwcJn3QLzLjFcxQxkjgFUcS6JTulPMAqTl/uehK7haRctfnP2Fl6mTeIjoEV+K5RKWEfNrTN3zBzil3zO7SpGxEPDgsEh0zN8kD3T+UiwlDlIyEkFJwiXqOOp6gdnoseapgSpI52Sjpiehpy2f0nvMOO9gPdNAuoXkNg/JZmrNFtwFF5RrICmO6pQcgL24/9RFYJr6W1t8EKE5SLAJs8QIojQFvUmX0mw/ButXRFeOR3MveqcM+8ZQrgppH7ZVrnlm97fRXspKZ/72RCek65tjLqZNuX5EEpgiUEz5EGGYYCyas7eidYX9OqAIsNpSRkhOQ9sDGvZKlhqCA/Qu/mOvwjgra7sPZikfBkFwBUxvEQ7HkyUYVctT2hyCR82D3vFkuUjNCuFC1zYWRXd1Rs/orHNDBdS0p4k0AGMToEvn9DGcciH18UTyimaoG7mFObS5Teue1aTwOO44E+efW1efwPnrUHb9+rNWXVFRT9mgjA37jl5n6GKW+2PtxAE0WA2t2PoxmmpJMFt9jzQZwPqZqNtZQlhUJSjMGSUGo=
